export const EMPLOYEETYPE = {
  INITIALIZEEMPLOYEETOSTORE: "INITIALIZEEMPLOYEETOSTORE",
  SETCURRENTUSER: "SETCURRENTUSER",
  SETLOADINGSTATUS: "SETLOADINGSTATUS",
  SETERROR: "SETERROR",
  SETSTATE: "SETSTATE",
};
