export const CARTTYPE = {
  SETCARTITEMS: "SETCARTITEMS",
  ADDCARTITEM: "ADDCARTITEM",
  REMOVECARTITEM: "REMOVECARTITEM",
  INCREMENTCARTITEM: "INCREMENTCARTITEM",
  DECREMENTCARTITEM: "DECREMENTCARTITEM",
  RESETCARTITEMS: "RESETCARTITEMS",
};
